feat: adding ai chatbot integration
TurningPointChatbot/counseling-training-chatbot pull request #67
Opened 2022-10-14 02:43 UTC by wric0003

- One new api endpoint
- Changes to chatbot.ts
- Changes to chabot page

2022-10-14 05:46 UTC, hbar0009 requested changes
All looks awesome, only thing is that it looks like there's a lot of repeated code between `[attempt_id].ts` and `_api.ts`.

Would it be possible to extract this repeated code into a function in `_api.ts`, and then call that function from `[attempt_id].ts`?

2022-10-14 06:24 UTC, Irate-Walrus commented
> All looks awesome, only thing is that it looks like there's a lot of repeated code between `[attempt_id].ts` and `_api.ts`.
> 
> Would it be possible to extract this repeated code into a function in `_api.ts`, and then call that function from `[attempt_id].ts`?

My bad, there isn't actually in anything being imported from  `_api.ts`. It can be gotten rid of entirely if you would like?

2022-10-14 06:26 UTC, hbar0009 commented
> > All looks awesome, only thing is that it looks like there's a lot of repeated code between `[attempt_id].ts` and `_api.ts`.
> > Would it be possible to extract this repeated code into a function in `_api.ts`, and then call that function from `[attempt_id].ts`?
> 
> My bad, there isn't actually in anything being imported from `_api.ts`. It can be gotten rid of entirely if you would like?

Yep that sounds good!

2022-10-16 05:52 UTC, hbar0009 submitted a review, later dismissed

2022-10-16 06:14 UTC, anna-giang approved these changes

2022-10-16 06:15 UTC, merged